# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Perl HowTo - Tipps, Tricks und Anleitungen"
email: perlhowto.github.io@gmail.com
description: "Perl HowTo - Tipps, Tricks und Anleitungen - Getting things done with Perl 5"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://perl-howto.github.io" # the base hostname & protocol for your site
github_repo_url: https://github.com/perl-howto/perl-howto.github.io

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author_full_name: "Thomas Fahle"
      author_url: "http://thomas-fahle.de"

gems:
  - jekyll-sitemap

